env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - import
  - prettier
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
    - singleQuote: true
  quotes:
    - error
    - single
overrides:
  - files:
      - handler.ts
    rules:
      import/prefer-default-export: off
      '@typescript-eslint/require-await': off
